version: "3.8"
services:
  backend:
    build: ./back-end
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://admin:secret123@mongo:27017/streaming-app?authSource=admin
      - PORT=5000
      - JWT_SECRET=guau
    depends_on:
      - mongo
    networks:
      - mi-red

  frontend:
    build: ./streaming-app
    ports:
      - "3000:80"
    networks:
      - mi-red

  mongo:
    image: mongo:6
    environment:
      - MONGO_INITDB_DATABASE=streaming-app
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret123
    ports:
      - "27017:27017"
    networks:
      - mi-red

networks:
  mi-red:
    driver: bridge
